### ISSUE TITLE
How is the Letters shader referenced in its VFX graph?

### ISSUE THREAD

**Issue by acerio98** [keijiro/ProcCharVfx#1]
I'm new to the Unity VFX graph but am trying to use this repo to understand a bit about how it works. 

However, when I look at the Letters graph, I don't quite understand how the Letters shader is referenced in the VFX graph beyond some implicit connection in the "Output Particle Quad" node. When I try to create my own "Output Particle Quad" node I can only select Texture2Ds, but would like to use a custom shader like you did. Could you tell me how the connection from the Visual Effect Master node in the Shader graph is made to this node in the VFX graph? Thanks.

**Comment by keijiro** [comment]
Try enabling experimental features: https://twitter.com/John_O_Really/status/1059921583865769986

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it if it still reproduces.

**Comment by acerio98** [comment]
Worked like a charm, thanks!
