### ISSUE TITLE
How to use "visual effect master" in shader graph?

### ISSUE THREAD

**Issue by emanonhero** [keijiro/ProcCharVfx#2]
Could you help me? I can't find any document.

**Comment by emanonhero** [comment]
![output](https://user-images.githubusercontent.com/21159676/72675470-84d5f380-3abf-11ea-8414-00d39231cb3c.png)
i don't understand why they are diffirent.

**Comment by keijiro** [comment]
Try enabling "Experimental Operators/Blocks".

https://twitter.com/John_O_Really/status/1059921583865769986

**Comment by keijiro** [comment]
I'm closing this issue now. Sorry but the question is not relevant to this repository. Please understand that this issue tracker is used to solve problems with this specific project.
