### ISSUE TITLE
Question about text

### ISSUE THREAD

**Issue by Kevdome3000** [keijiro/ProcCharVfx#3]
what would be the best approach if I wanted to use the letters vfx/ shadergraph to actually print out  english characters?

thanks in advanced!

**Comment by keijiro** [comment]
You have to use different approaches with VFX Graph and Shader Graph. For VFX Graph, I think using sheet animation is the easiest way to handle those kind of things (control frame to change letter).

I'm closing this issue now as the question is not relevant to this repository. I'm sorry, but please understand that this issue tracker is dedicated to solve issues happened in this specific project. I'd recommend using the official forum to solve general questions.
